# netlify.toml

[build]
command = "npm run build"
publish = "dist"
# only rebuild if src, public, or package.json changed
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./src ./public ./package.json"

# Always serve index.html for client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# 1) Long‑term cache for JS/CSS
[[headers]]
for = "/*.(js|mjs|css)"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# 2) Long‑term cache + CORS for fonts
[[headers]]
for = "/*.(woff|woff2)"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
Access-Control-Allow-Origin = "*"

# 3) Long‑term cache for modern image formats
[[headers]]
for = "/*.(svg|avif|webp|png|jpg|jpeg|gif)"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"


# 4) HTML: no‑cache but revalidate + security
[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://www.google-analytics.com"
